# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

nodes_config = (JSON.parse(File.read("nodes.json")))['nodes']

Vagrant.configure("2") do |config|
  nodes_config.each do |node|
    node_name   = node[0] # name of node
    node_values = node[1] # content of node

    config.vm.box = node_values[':box']

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    config.vm.define node_name do |config|
      # configures all forwarding ports in JSON array
      ports = node_values['ports']
      ports.each do |port|
        config.vm.network :forwarded_port,
          host:  port[':host'],
          guest: port[':guest'],
          id:    port[':id']
      end

      config.vm.hostname = node_values[':fqdn'] 
      config.vm.network :private_network, ip: node_values[':ip']

      memory = node_values[:ram] ? node_values[:ram] : 256;
      config.vm.provider "virtualbox" do |vb|
        vb.customize [
          'modifyvm', :id,
          '--name', node_values[':fqdn'],
          '--memory', memory.to_s
        ]
      end

      node_values[':bootstrap'].each do |script|
        config.vm.provision :shell, :path => script
      end

    end
  end
end
